services:
  - type: web
    name: hng12-stage1
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -k uvicorn.workers.UvicornWorker main:app"
    plan: free
    region: oregon
